import Link from "next/link";
import { notFound } from "next/navigation";
import { AppShell } from "../../components/app-shell";
import { ChevronLeft, Download, FileText, Paperclip, Printer } from "../../components/icons";
import { Button, PageHeader } from "../../components/ui";
import { getRequestDetail } from "../../lib/live-data";

export default async function RequestDetailPage({ params }: PageProps<"/requests/[id]">) {
  const { id } = await params;
  const { data, error } = await getRequestDetail(id);
  if (!data && !error) notFound();
  if (!data) return <AppShell><PageHeader title="ไม่สามารถเปิดคำขอได้" description="ฐานข้อมูลยังไม่พร้อมใช้งาน"/><div role="alert" className="mt-5 border border-red-300 bg-[var(--red-soft)] p-4 text-[var(--red)]">{error}</div></AppShell>;
  const department = data.departments as { name_th?: string } | null;
  const requester = data.profiles as { full_name?: string; position_title?: string } | null;
  const items = (data.request_items ?? []) as Array<Record<string, unknown>>;
  const attachments = (data.request_attachments ?? []) as Array<Record<string, unknown>>;
  const actions = (data.workflow_actions ?? []) as Array<Record<string, unknown>>;
  return <AppShell><PageHeader title={String(data.request_no)} description={String(data.title)} action={<div className="flex gap-2"><Button variant="secondary"><Printer size={17}/>พิมพ์</Button></div>}/><Link href="/requests" className="my-4 inline-flex items-center gap-1 font-semibold hover:text-[var(--orange-dark)]"><ChevronLeft size={17}/>กลับไปคำขอของฉัน</Link>
    <div className="grid gap-5 xl:grid-cols-[minmax(0,1fr)_320px]"><article className="border border-[var(--line-dark)] bg-[var(--paper)]"><div className="flex flex-col gap-5 border-b border-[var(--line)] p-5 sm:flex-row"><div className="flex h-16 w-16 shrink-0 items-center justify-center border border-[var(--line-dark)]"><FileText size={30}/></div><div className="flex-1"><h1 className="text-xl font-bold">{String(data.title)}</h1><p className="mt-2 text-sm text-stone-600">{String(data.rationale)}</p></div><dl className="grid grid-cols-2 gap-x-5 gap-y-2 text-sm"><dt className="text-stone-500">ประเภท</dt><dd className="font-semibold">{data.kind==="hire"?"ขอจ้าง":"ขอซื้อ"}</dd><dt className="text-stone-500">สถานะ</dt><dd className="font-semibold">{String(data.status)}</dd><dt className="text-stone-500">ขั้นตอน</dt><dd className="font-semibold">{String(data.current_step)}</dd><dt className="text-stone-500">วงเงิน</dt><dd className="font-bold tabular-nums">{Number(data.estimated_amount).toLocaleString("th-TH",{minimumFractionDigits:2})}</dd></dl></div>
      <section className="p-5"><h2 className="text-lg font-bold">รายการสินค้า/บริการ</h2>{items.length===0?<p className="mt-3 border border-[var(--line)] p-4 text-sm text-stone-600">ยังไม่มีรายการ</p>:<div className="scrollbar-thin mt-3 overflow-x-auto"><table className="w-full min-w-[640px] border-collapse"><thead className="bg-stone-100"><tr>{["ลำดับ","รายการ","จำนวน","หน่วย","ราคาต่อหน่วย","จำนวนเงิน"].map((heading)=><th key={heading} className="border border-[var(--line)] p-2 text-left text-xs">{heading}</th>)}</tr></thead><tbody>{items.sort((a,b)=>Number(a.line_no)-Number(b.line_no)).map((item)=><tr key={String(item.line_no)}><td className="border border-[var(--line)] p-2 text-center">{String(item.line_no)}</td><td className="border border-[var(--line)] p-2">{String(item.description)}</td><td className="border border-[var(--line)] p-2 text-right">{String(item.quantity)}</td><td className="border border-[var(--line)] p-2">{String(item.unit)}</td><td className="border border-[var(--line)] p-2 text-right">{Number(item.unit_price).toLocaleString("th-TH",{minimumFractionDigits:2})}</td><td className="border border-[var(--line)] p-2 text-right">{Number(item.total_amount).toLocaleString("th-TH",{minimumFractionDigits:2})}</td></tr>)}</tbody></table></div>}</section>
      <section className="border-t border-[var(--line)] p-5"><h2 className="text-lg font-bold">เอกสารแนบ</h2>{attachments.length===0?<p className="mt-3 text-sm text-stone-600">ไม่มีเอกสารแนบ</p>:<div className="mt-3 divide-y divide-[var(--line)] border border-[var(--line)]">{attachments.map((file)=><div key={String(file.id)} className="flex items-center gap-3 p-3"><Paperclip size={17}/><span className="min-w-0 flex-1 truncate font-medium">{String(file.file_name)}</span><span className="text-xs text-stone-500">{Math.ceil(Number(file.size_bytes)/1024)} KB</span><button disabled title="เตรียมเชื่อม signed URL" className="p-2 opacity-40"><Download size={17}/></button></div>)}</div>}</section></article>
      <aside className="space-y-5"><section className="border border-[var(--line-dark)] bg-[var(--paper)]"><h2 className="border-b border-[var(--line)] p-4 font-bold">ข้อมูลผู้ยื่น</h2><dl className="space-y-3 p-4 text-sm"><div><dt className="text-stone-500">ชื่อ</dt><dd className="font-semibold">{requester?.full_name||"—"}</dd></div><div><dt className="text-stone-500">ตำแหน่ง</dt><dd>{requester?.position_title||"—"}</dd></div><div><dt className="text-stone-500">หน่วยงาน</dt><dd>{department?.name_th||"—"}</dd></div><div><dt className="text-stone-500">ปีงบประมาณ / แหล่งเงิน</dt><dd>{String(data.budget_year)} · {String(data.fund_source)}</dd></div></dl></section><section className="border border-[var(--line-dark)] bg-[var(--paper)]"><h2 className="border-b border-[var(--line)] p-4 font-bold">ประวัติการดำเนินการ</h2>{actions.length===0?<p className="p-4 text-sm text-stone-600">ยังไม่มีประวัติ</p>:<ol className="divide-y divide-[var(--line)]">{actions.map((action)=><li key={String(action.id)} className="p-4"><div className="font-semibold">{String(action.action)}</div><div className="mt-1 text-xs text-stone-500">{new Intl.DateTimeFormat("th-TH",{dateStyle:"medium",timeStyle:"short"}).format(new Date(String(action.created_at)))}</div>{action.comment?<p className="mt-2 text-sm">{String(action.comment)}</p>:null}</li>)}</ol>}</section></aside></div>
  </AppShell>;
}
