"use client";

import { useState } from "react";
import { Check, CheckCircle2, Clock3, Download, FileText, Paperclip, RotateCcw, UserRound, X } from "../../components/icons";
import { Button } from "../../components/ui";

const records = [
 { id:"PR6705-00045", title:"จัดซื้อวัสดุสำนักงาน จำนวน 12 รายการ", amount:"24,750.00", when:"ปัจจุบัน", type:"ขอซื้อ", date:"15 พ.ค. 2567", department:"สำนักงานเลขานุการ", fund:"งบประมาณแผ่นดิน", requester:"นางสาวจิราพร แสงดี", role:"เจ้าหน้าที่บริหารงานทั่วไป", items:[["กระดาษถ่ายเอกสาร A4 80 แกรม","10","รีม","120.00","1,200.00"],["แฟ้มสันกว้าง 3 นิ้ว","20","เล่ม","75.00","1,500.00"]] },
 { id:"PR6705-00044", title:"จัดซื้อวัสดุคอมพิวเตอร์ จำนวน 5 รายการ", amount:"58,900.00", when:"วันนี้", type:"ขอซื้อ", date:"14 พ.ค. 2567", department:"งานเทคโนโลยีสารสนเทศ", fund:"เงินรายได้", requester:"นายกิตติศักดิ์ ใจมั่น", role:"นักวิชาการคอมพิวเตอร์", items:[["จอภาพขนาด 27 นิ้ว","5","เครื่อง","9,900.00","49,500.00"],["อุปกรณ์สำรองไฟ","2","เครื่อง","4,700.00","9,400.00"]] },
 { id:"PR6705-00043", title:"จ้างเหมาบริการทำความสะอาด", amount:"15,600.00", when:"เมื่อวาน", type:"ขอจ้าง", date:"13 พ.ค. 2567", department:"งานอาคารสถานที่", fund:"เงินรายได้", requester:"นางสาววราภรณ์ คงดี", role:"เจ้าหน้าที่บริหารงานทั่วไป", items:[["บริการทำความสะอาดพื้นที่สำนักงาน","1","งาน","15,600.00","15,600.00"]] },
 { id:"PR6705-00042", title:"จัดซื้อครุภัณฑ์สำนักงาน", amount:"32,400.00", when:"เมื่อวาน", type:"ขอซื้อ", date:"13 พ.ค. 2567", department:"งานบริหารทั่วไป", fund:"งบประมาณแผ่นดิน", requester:"นายธนกร พูนสุข", role:"เจ้าหน้าที่ธุรการ", items:[["เก้าอี้สำนักงาน","6","ตัว","5,400.00","32,400.00"]] },
];

export function ReviewWorkspace({ id }: { id: string }) {
 const [notice,setNotice]=useState<string | null>(null); const [activeId,setActiveId]=useState(id); const [comment,setComment]=useState(""); const [actionDone,setActionDone]=useState(false);
 const record = records.find((item)=>item.id===activeId) ?? records[0];
 const decide = (kind: "approve"|"return") => { if(kind==="return"&&!comment.trim()){setNotice("กรุณาระบุเหตุผลก่อนส่งกลับแก้ไข");return;} setActionDone(true); setNotice(kind==="approve"?"เห็นชอบและส่งต่อแล้ว (จำลอง)":"ส่งกลับแก้ไขแล้ว (จำลอง)"); };
 return <><div className="grid min-h-[calc(100vh-12rem)] border border-[var(--line-dark)] bg-[var(--paper)] xl:grid-cols-[260px_minmax(0,1fr)] 2xl:grid-cols-[280px_minmax(600px,1fr)_300px]">
  <aside className="border-b border-[var(--line-dark)] xl:border-b-0 xl:border-r"><div className="border-b border-[var(--line)] p-4"><h2 className="text-lg font-bold">งานรอตรวจสอบ</h2><p className="mt-1 text-xs text-stone-500">แสดงตัวอย่าง {records.length} จาก 27 รายการ</p></div><div className="divide-y divide-[var(--line)]">{records.map((item)=><button key={item.id} onClick={()=>{setActiveId(item.id);setActionDone(false);setComment("");}} aria-pressed={activeId===item.id} className={`w-full p-4 text-left hover:bg-orange-50 ${activeId===item.id?"bg-[var(--orange-soft)] outline outline-1 -outline-offset-1 outline-[var(--orange)]":""}`}><div className="flex items-center gap-2"><FileText size={17}/><span className="font-bold">{item.id}</span>{activeId===item.id&&<span className="ml-auto border border-[var(--orange)] bg-white px-1.5 text-xs text-[var(--orange-dark)]">รอตรวจ</span>}</div><div className="mt-2 line-clamp-2 text-sm font-semibold">{item.title}</div><div className="mt-2 flex justify-between text-xs text-stone-500"><span>{item.amount} บาท</span><span>{item.when}</span></div></button>)}</div></aside>
  <article className="min-w-0"><div className="scrollbar-thin flex gap-0 overflow-x-auto border-b border-[var(--line)] bg-stone-50 p-3">{["สร้างคำขอ","ตรวจสอบเบื้องต้น","ตรวจสอบเอกสาร","เห็นชอบ","อนุมัติ","เสร็จสิ้น"].map((s,i)=><div key={s} className={`min-w-32 flex-1 border-y border-r border-[var(--line)] px-3 py-2 text-center text-xs font-semibold first:border-l ${i===2?"bg-[var(--orange)] text-white":"bg-white"}`}>{i+1}. {s}</div>)}</div>
   <div className="p-5 lg:p-6"><div className="flex flex-col gap-5 border-b border-[var(--line)] pb-5 lg:flex-row lg:items-start"><div className="flex h-16 w-16 shrink-0 items-center justify-center border border-[var(--line-dark)]"><FileText size={30}/></div><div className="flex-1"><div className="flex flex-wrap items-center gap-3"><h1 className="text-2xl font-bold tracking-[-.02em]">{activeId}</h1><span className={`border px-2 py-1 text-xs font-bold ${actionDone?"border-green-300 bg-[var(--green-soft)] text-[var(--green)]":"border-[var(--blue)] bg-[var(--blue-soft)] text-[var(--blue)]"}`}>{actionDone?"ดำเนินการแล้ว":"รอตรวจสอบ"}</span></div><p className="mt-2 text-lg font-semibold">{record.title}</p><p className="mt-1 text-sm text-stone-600">งบประมาณ {record.amount} บาท</p></div><div className="grid grid-cols-2 gap-x-6 gap-y-2 text-sm"><span className="text-stone-500">ประเภทคำขอ</span><strong>{record.type}</strong><span className="text-stone-500">วันที่สร้าง</span><strong>{record.date}</strong><span className="text-stone-500">หน่วยงาน</span><strong>{record.department}</strong><span className="text-stone-500">แหล่งเงิน</span><strong>{record.fund}</strong></div></div>
   <section className="mt-6"><h2 className="text-lg font-bold">รายการสินค้า/บริการ</h2><div className="scrollbar-thin mt-3 overflow-x-auto"><table className="w-full min-w-[640px] border-collapse"><thead className="bg-stone-100"><tr>{["ลำดับ","รายการ","จำนวน","หน่วย","ราคาต่อหน่วย","จำนวนเงิน"].map(h=><th key={h} className="border border-[var(--line)] p-2 text-left text-xs">{h}</th>)}</tr></thead><tbody>{[["กระดาษถ่ายเอกสาร A4 80 แกรม (500 แผ่น)","10","รีม","120.00","1,200.00"],["แฟ้มสันกว้าง 3 นิ้ว","20","เล่ม","75.00","1,500.00"],["ปากกาลูกลื่น 0.5 มม. (น้ำเงิน)","50","ด้าม","8.00","400.00"],["ซองเอกสารน้ำตาล A4","50","ซอง","3.50","175.00"]].map((r,i)=><tr key={i}><td className="border border-[var(--line)] p-2 text-center">{i+1}</td>{r.map((v,j)=><td key={j} className={`border border-[var(--line)] p-2 ${j>0?"text-right":""}`}>{v}</td>)}</tr>)}</tbody></table></div><button className="mt-3 w-full border border-[var(--line)] p-2 text-sm font-semibold hover:bg-stone-100">ดูรายการทั้งหมด 12 รายการ</button></section>
   <section className="mt-6 border-y border-[var(--line-dark)] bg-stone-50"><dl className="grid sm:grid-cols-4"><div className="p-4"><dt className="text-xs text-stone-500">วงเงินงบประมาณ</dt><dd className="mt-1 font-bold">30,000.00 บาท</dd></div><div className="border-t border-[var(--line)] p-4 sm:border-l sm:border-t-0"><dt className="text-xs text-stone-500">รวมยอดขอซื้อ</dt><dd className="mt-1 font-bold">24,750.00 บาท</dd></div><div className="border-t border-[var(--line)] p-4 sm:border-l sm:border-t-0"><dt className="text-xs text-stone-500">ภาษีมูลค่าเพิ่ม (7%)</dt><dd className="mt-1 font-bold">1,620.09 บาท</dd></div><div className="border-t border-[var(--line)] p-4 sm:border-l sm:border-t-0"><dt className="text-xs text-stone-500">รวมจำนวนเงินทั้งสิ้น</dt><dd className="mt-1 text-xl font-bold text-[var(--orange-dark)]">24,750.00 บาท</dd></div></dl></section>
   <section className="mt-6"><h2 className="text-lg font-bold">เอกสารแนบ</h2><div className="mt-3 divide-y divide-[var(--line)] border border-[var(--line)]">{[["ใบเสนอราคา_บจก.สมาร์ทออฟฟิศ.pdf","245 KB"],["สเปคสินค้า_วัสดุสำนักงาน.pdf","312 KB"],["แผนเปรียบเทียบราคา.png","198 KB"]].map(([n,s])=><div key={n} className="flex items-center gap-3 p-3"><Paperclip size={17}/><span className="min-w-0 flex-1 truncate font-medium">{n}</span><span className="text-xs text-stone-500">{s}</span><button aria-label={`ดาวน์โหลด ${n}`} className="p-2 hover:bg-stone-100"><Download size={17}/></button></div>)}</div></section></div>
  </article>
  <aside className="border-t border-[var(--line-dark)] xl:col-span-2 2xl:col-span-1 2xl:border-l 2xl:border-t-0"><div className="sticky top-20"><div className="border-b border-[var(--line)] p-4"><h2 className="text-lg font-bold">ข้อมูลการตรวจสอบ</h2></div><div className="border-b border-[var(--line)] p-4"><div className="flex gap-3"><UserRound/><div><div className="text-xs text-stone-500">ผู้ขอ</div><div className="font-bold">นางสาวจิราพร แสงดี</div><div className="text-xs text-stone-500">เจ้าหน้าที่บริหารงานทั่วไป</div></div></div></div><div className="border-b border-[var(--line)] p-4"><div className="flex items-center gap-3"><Clock3/><div><div className="text-xs text-stone-500">ระยะเวลาดำเนินการ</div><div className="text-xl font-bold tabular-nums">00:45:27</div></div></div></div><div className="p-4"><label className="font-semibold" htmlFor="comment">ความคิดเห็น <span className="text-xs font-normal text-stone-500">(บังคับเมื่อส่งกลับ)</span></label><textarea id="comment" value={comment} onChange={(event)=>setComment(event.target.value.slice(0,1000))} disabled={actionDone} className="mt-2 min-h-28 w-full border border-[var(--line-dark)] p-3 disabled:bg-stone-100" placeholder="ระบุความคิดเห็นหรือเหตุผลที่ต้องแก้ไข"/><div className="mt-1 text-right text-xs text-stone-500">{comment.length.toLocaleString("th-TH")} / 1,000</div><Button disabled={actionDone} className="mt-4 w-full" onClick={()=>decide("approve")}><Check size={18}/>เห็นชอบและส่งต่อ</Button><Button disabled={actionDone} variant="secondary" className="mt-2 w-full" onClick={()=>decide("return")}><RotateCcw size={18}/>ส่งกลับแก้ไข</Button></div><div className="border-t border-[var(--line)] p-4"><h3 className="font-bold">ประวัติการดำเนินการ</h3><ol className="mt-4 space-y-5 border-l border-[var(--line-dark)] pl-5">{actionDone&&<li className="relative"><span className="absolute -left-[25px] top-1 h-2.5 w-2.5 rounded-full bg-[var(--green)]"/><div className="text-sm font-semibold">ดำเนินการโดยเจ้าหน้าที่พัสดุ</div><div className="text-xs text-stone-500">เมื่อสักครู่ · ข้อมูลจำลอง</div></li>}{[["ตรวจสอบเอกสาร","โดย ธนพร จ. · ปัจจุบัน"],["ตรวจสอบเบื้องต้น","โดย พิชญา ใจดี · 15 พ.ค."],["สร้างคำขอ","โดย จิราพร แสงดี · 15 พ.ค."]].map(([a,b],i)=><li key={a} className="relative"><span className={`absolute -left-[25px] top-1 h-2.5 w-2.5 rounded-full ${i===0?"bg-[var(--orange)]":"bg-stone-400"}`}/><div className="text-sm font-semibold">{a}</div><div className="text-xs text-stone-500">{b}</div></li>)}</ol></div></div></aside>
 </div>{notice&&<div role="status" className="fixed bottom-5 right-5 z-50 flex max-w-sm items-center gap-3 border border-[var(--green)] bg-[var(--green-soft)] p-4 text-[var(--green)] shadow-lg"><CheckCircle2/><span className="font-semibold">{notice}</span><button onClick={()=>setNotice(null)} aria-label="ปิด"><X size={17}/></button></div>}</>;
}
