"use client";

import { useRef, useState } from "react";
import Link from "next/link";
import { AppShell } from "../../components/app-shell";
import { Check, ChevronLeft, ChevronRight, FileText, Paperclip, Plus, Save, Upload, X } from "../../components/icons";
import { Button, Field, PageHeader, inputClass } from "../../components/ui";

const steps = ["ข้อมูลคำขอ", "รายการพัสดุ/บริการ", "งบประมาณ", "เอกสารแนบ", "ตรวจสอบและส่ง"];

export default function NewRequestPage() {
 const [step, setStep] = useState(0); const [notice, setNotice] = useState<string | null>(null); const [requestType,setRequestType]=useState<"ซื้อ"|"จ้าง">("ซื้อ"); const [uploaded,setUploaded]=useState(false); const formRef=useRef<HTMLFormElement>(null);
 return <AppShell><PageHeader title="สร้างคำขอหลักการขอซื้อ/จ้าง" description="เลขคำขอจะออกอัตโนมัติเมื่อส่งคำขอเข้าสู่กระบวนการ" action={<div className="flex gap-2"><Button variant="secondary" onClick={()=>setNotice("บันทึกร่างแล้วเมื่อสักครู่")}><Save size={17}/>บันทึกร่าง</Button></div>}/>
  {notice && <div role="status" className="mt-4 flex items-center gap-2 border border-green-300 bg-[var(--green-soft)] p-3 text-[var(--green)]"><Check size={18}/><span className="font-semibold">{notice}</span><button onClick={()=>setNotice(null)} className="ml-auto" aria-label="ปิดข้อความ"><X size={17}/></button></div>}
  <ol className="mt-6 grid border border-[var(--line-dark)] bg-[var(--paper)] md:grid-cols-5">{steps.map((s,i)=><li key={s} className={`relative flex items-center gap-3 border-b border-[var(--line)] p-3 last:border-b-0 md:border-b-0 md:border-r md:last:border-r-0 ${i===step ? "bg-[var(--orange)] text-white" : i<step ? "bg-[var(--green-soft)]" : ""}`}><span className={`flex h-7 w-7 shrink-0 items-center justify-center border ${i===step ? "border-white" : "border-[var(--line-dark)] bg-white"}`}>{i<step?<Check size={16}/>:i+1}</span><span className="text-sm font-semibold">{s}</span></li>)}</ol>
  <form ref={formRef} onSubmit={(e)=>e.preventDefault()} className="mt-5 border border-[var(--line-dark)] bg-[var(--paper)]"><div className="border-b border-[var(--line)] px-5 py-4"><h2 className="text-xl font-bold">{steps[step]}</h2><p className="mt-1 text-sm text-stone-600">ขั้นตอนที่ {step+1} จาก {steps.length} · ช่องที่มีเครื่องหมาย * จำเป็นต้องกรอก</p></div>
    <div className="p-5 sm:p-6">{step===0 && <div className="grid gap-5 lg:grid-cols-2"><Field label="ประเภทคำขอ" required><div className="grid grid-cols-2 gap-3">{(["ซื้อ","จ้าง"] as const).map(type=><label key={type} className={`flex cursor-pointer items-center gap-3 border p-4 font-semibold ${requestType===type?"border-[var(--orange)] bg-[var(--orange-soft)]":"border-[var(--line-dark)]"}`}><input type="radio" name="type" checked={requestType===type} onChange={()=>setRequestType(type)}/> ขอ{type}</label>)}</div></Field><Field label="หน่วยงานผู้ขอ" required><select required className={inputClass} defaultValue="สำนักงานเลขานุการ"><option>สำนักงานเลขานุการ</option><option>คณะวิทยาศาสตร์</option></select></Field><div className="lg:col-span-2"><Field label="ชื่อเรื่อง" required hint="สรุปสิ่งที่ต้องการซื้อหรือจ้างให้เข้าใจได้ในหนึ่งบรรทัด"><input required className={inputClass} defaultValue="จัดซื้อวัสดุสำนักงานประจำปีงบประมาณ 2567"/></Field></div><div className="lg:col-span-2"><Field label="เหตุผลและความจำเป็น" required><textarea required className={`${inputClass} min-h-32 py-3`} defaultValue="เพื่อใช้สนับสนุนการปฏิบัติงานของสำนักงานเลขานุการ และทดแทนวัสดุคงคลังที่ใกล้หมด"/></Field></div><Field label="วันที่ต้องการใช้" required><input required type="date" className={inputClass}/></Field><Field label="ผู้ประสานงาน"><input className={inputClass} defaultValue="ธนพร จ."/></Field></div>}
    {step===1 && <div><div className="scrollbar-thin overflow-x-auto"><table className="w-full min-w-[760px] border-collapse"><thead className="bg-stone-100"><tr>{["ลำดับ","รายการ","จำนวน","หน่วย","ราคาต่อหน่วย","จำนวนเงิน",""] .map(h=><th key={h} className="border border-[var(--line)] p-3 text-left text-xs">{h}</th>)}</tr></thead><tbody>{[["กระดาษถ่ายเอกสาร A4 80 แกรม","10","รีม","120.00","1,200.00"],["แฟ้มสันกว้าง 3 นิ้ว","20","เล่ม","75.00","1,500.00"],["ปากกาลูกลื่น 0.5 มม.","50","ด้าม","8.00","400.00"]].map((r,i)=><tr key={i}><td className="border border-[var(--line)] p-3 text-center">{i+1}</td>{r.map((v,j)=><td key={j} className="border border-[var(--line)] p-2"><input className="min-h-10 w-full border border-transparent bg-transparent px-2 hover:border-[var(--line)]" defaultValue={v}/></td>)}<td className="border border-[var(--line)] p-2"><button className="p-2 text-[var(--red)]" aria-label={`ลบรายการ ${i+1}`}><X size={17}/></button></td></tr>)}</tbody><tfoot><tr><td colSpan={5} className="border border-[var(--line)] p-3 text-right font-bold">รวมประมาณการ</td><td className="border border-[var(--line)] p-3 text-right text-lg font-bold text-[var(--orange-dark)]">3,100.00</td><td className="border border-[var(--line)]"/></tr></tfoot></table></div><Button variant="secondary" className="mt-4"><Plus size={17}/>เพิ่มรายการ</Button></div>}
    {step===2 && <div className="grid gap-5 lg:grid-cols-2"><Field label="ปีงบประมาณ" required><select className={inputClass}><option>2567</option></select></Field><Field label="แหล่งเงิน" required><select className={inputClass}><option>เงินงบประมาณแผ่นดิน</option><option>เงินรายได้</option></select></Field><Field label="แผนงาน / โครงการ" required><select className={inputClass}><option>แผนงานบริหารทั่วไป</option></select></Field><Field label="หมวดรายจ่าย" required><select className={inputClass}><option>ค่าวัสดุ</option></select></Field><div className="lg:col-span-2 border border-[var(--line-dark)] bg-stone-50 p-5"><h3 className="font-bold">ข้อมูลวงเงิน (ข้อมูลจำลอง)</h3><dl className="mt-4 grid gap-4 sm:grid-cols-3"><div><dt className="text-xs text-stone-500">งบประมาณคงเหลือ</dt><dd className="mt-1 text-xl font-bold">125,000.00 บาท</dd></div><div><dt className="text-xs text-stone-500">ยอดคำขอนี้</dt><dd className="mt-1 text-xl font-bold text-[var(--orange-dark)]">3,100.00 บาท</dd></div><div><dt className="text-xs text-stone-500">คงเหลือหลังรายการ</dt><dd className="mt-1 text-xl font-bold text-[var(--green)]">121,900.00 บาท</dd></div></dl></div></div>}
    {step===3 && <div><div className="border-2 border-dashed border-[var(--line-dark)] bg-stone-50 p-10 text-center"><Upload className="mx-auto" size={34}/><h3 className="mt-3 text-lg font-bold">ลากไฟล์มาวาง หรือเลือกไฟล์จากเครื่อง</h3><p className="mt-1 text-sm text-stone-600">รองรับ PDF, JPG, PNG, DOCX, XLSX ขนาดไม่เกิน 20 MB ต่อไฟล์</p><Button variant="secondary" className="mt-4" onClick={()=>setUploaded(true)}><Paperclip size={17}/>เลือกไฟล์จำลอง</Button></div>{uploaded&&<div role="status" className="mt-3 border border-green-300 bg-[var(--green-soft)] p-3 text-sm font-semibold text-[var(--green)]">เพิ่มไฟล์ตัวอย่างแล้วสำเร็จ</div>}<div className="mt-5 border border-[var(--line)]"><div className="flex items-center gap-3 border-b border-[var(--line)] p-3"><FileText/><div className="flex-1"><div className="font-semibold">ใบเสนอราคา_วัสดุสำนักงาน.pdf</div><div className="text-xs text-stone-500">245 KB · อัปโหลดแล้ว</div></div><Check className="text-[var(--green)]"/></div><div className="flex items-center gap-3 p-3"><FileText/><div className="flex-1"><div className="font-semibold">รายละเอียดคุณลักษณะ.pdf</div><div className="text-xs text-stone-500">312 KB · อัปโหลดแล้ว</div></div><Check className="text-[var(--green)]"/></div></div></div>}
    {step===4 && <div className="grid gap-5 lg:grid-cols-[1fr_320px]"><div className="space-y-5"><section className="border border-[var(--line)]"><h3 className="border-b border-[var(--line)] bg-stone-100 p-3 font-bold">ข้อมูลคำขอ</h3><dl className="grid gap-4 p-4 sm:grid-cols-2"><div><dt className="text-xs text-stone-500">ประเภท</dt><dd className="font-semibold">ขอ{requestType}</dd></div><div><dt className="text-xs text-stone-500">หน่วยงาน</dt><dd className="font-semibold">สำนักงานเลขานุการ</dd></div><div className="sm:col-span-2"><dt className="text-xs text-stone-500">ชื่อเรื่อง</dt><dd className="font-semibold">จัดซื้อวัสดุสำนักงานประจำปีงบประมาณ 2567</dd></div></dl></section><section className="border border-[var(--line)] p-4"><h3 className="font-bold">รายการและงบประมาณ</h3><p className="mt-2 text-sm">3 รายการ · เงินงบประมาณแผ่นดิน · รวมประมาณการ <strong>3,100.00 บาท</strong></p></section></div><aside className="border border-[var(--orange)] bg-[var(--orange-soft)] p-5"><h3 className="font-bold">เมื่อส่งคำขอแล้ว</h3><ol className="mt-4 space-y-3 text-sm"><li className="flex gap-2"><span className="font-bold">1.</span>ระบบออกเลขคำขออัตโนมัติ</li><li className="flex gap-2"><span className="font-bold">2.</span>ล็อกข้อมูลฉบับที่ส่ง</li><li className="flex gap-2"><span className="font-bold">3.</span>ส่งให้เจ้าหน้าที่พัสดุตรวจสอบ</li><li className="flex gap-2"><span className="font-bold">4.</span>แจ้งเตือนผู้เกี่ยวข้อง</li></ol></aside></div>}
    </div><div className="flex flex-wrap items-center justify-between gap-3 border-t border-[var(--line)] bg-stone-50 p-4"><Link href="/requests" className="inline-flex min-h-10 items-center gap-2 px-3 font-semibold hover:underline"><ChevronLeft size={17}/>ยกเลิกและกลับ</Link><div className="flex gap-2">{step>0&&<Button variant="secondary" onClick={()=>setStep(step-1)}><ChevronLeft size={17}/>ย้อนกลับ</Button>}<button type="button" onClick={()=>{ if(step<steps.length-1){ if(step===0&&!formRef.current?.reportValidity()) return; setStep(step+1); } else setNotice("ส่งคำขอเข้าสู่ขั้นตอนเจ้าหน้าที่พัสดุตรวจสอบแล้ว (จำลอง)"); }} className="inline-flex min-h-10 items-center gap-2 border border-[var(--orange-dark)] bg-[var(--orange)] px-4 font-semibold text-white hover:bg-[var(--orange-dark)]">{step===steps.length-1?"ยืนยันและส่งคำขอ":"บันทึกและไปต่อ"}<ChevronRight size={17}/></button></div></div>
  </form>
 </AppShell>;
}
