import { AppShell } from "../components/app-shell";
import { ChevronRight, Clock3, Filter } from "../components/icons";
import { Button, PageHeader, StatusBadge } from "../components/ui";
import { getMyTasks } from "../lib/live-data";
import Link from "next/link";

export default async function TasksPage() {
 const { rows: requests, error } = await getMyTasks();
 return <AppShell><PageHeader title="งานรอตรวจสอบ" description="รายการที่ถูกมอบหมายให้คุณในฐานะเจ้าหน้าที่พัสดุ"/>
  {error&&<div role="alert" className="mt-5 border border-red-300 bg-[var(--red-soft)] p-4 text-[var(--red)]"><strong>ยังอ่านงานจากฐานข้อมูลไม่ได้</strong><p className="mt-1 text-sm">กรุณารัน migration ก่อนใช้งาน · {error}</p></div>}
  <div className="mt-6 grid gap-5 xl:grid-cols-[minmax(0,1fr)_320px]"><section className="border border-[var(--line-dark)] bg-[var(--paper)]"><div className="flex flex-wrap gap-2 border-b border-[var(--line)] p-4"><button className="min-h-10 bg-[var(--graphite)] px-4 font-semibold text-white">ทั้งหมด 5</button><button className="min-h-10 border border-[var(--line)] px-4 font-semibold">ใกล้ครบกำหนด 2</button><button className="min-h-10 border border-[var(--line)] px-4 font-semibold text-[var(--red)]">เกินกำหนด 2</button><Button variant="secondary" className="ml-auto"><Filter size={16}/>ตัวกรอง</Button></div><div className="divide-y divide-[var(--line)]">{requests.slice(0,5).map((r,i)=><Link href={`/requests/${r.id}`} key={r.id} className={`group grid gap-3 p-4 hover:bg-orange-50/60 sm:grid-cols-[auto_1fr_auto] ${r.status === "เกินกำหนด" ? "hazard" : ""}`}><div className="flex h-11 w-11 items-center justify-center border border-[var(--line-dark)] bg-white font-bold">{i+1}</div><div className="bg-[var(--paper)]/90 px-2"><div className="flex flex-wrap items-center gap-2"><span className="font-bold">{r.id}</span><StatusBadge status={r.status}/></div><h2 className="mt-1 font-semibold">{r.title}</h2><p className="mt-1 text-xs text-stone-600">{r.requester} · {r.unit} · {r.amount.toLocaleString("th-TH")} บาท</p></div><div className="flex items-center gap-3 bg-[var(--paper)]/90 px-2"><div className="text-right text-xs"><div className="font-semibold">กำหนด {r.due}</div><div className="mt-1 text-stone-500">รอมาแล้ว {i+1} วัน</div></div><ChevronRight className="transition-transform group-hover:translate-x-1"/></div></Link>)}</div></section>
  <aside className="space-y-5"><div className="border border-[var(--line-dark)] bg-[var(--paper)]"><h2 className="border-b border-[var(--line)] p-4 text-lg font-bold">สรุปงานของฉัน</h2><dl className="divide-y divide-[var(--line)]">{[["รอตรวจสอบ","5"],["ใกล้ครบกำหนด","2"],["เกินกำหนด","2"],["เสร็จสิ้นสัปดาห์นี้","18"]].map(([k,v])=><div key={k} className="flex items-center justify-between p-4"><dt>{k}</dt><dd className="text-2xl font-bold tabular-nums text-[var(--orange)]">{v}</dd></div>)}</dl></div><div className="border border-[var(--line-dark)] bg-[var(--amber-soft)] p-4"><div className="flex gap-3"><Clock3 className="shrink-0 text-[var(--amber)]"/><div><h2 className="font-bold">SLA การตรวจสอบ</h2><p className="mt-1 text-sm text-stone-700">ดำเนินการภายใน 2 วันทำการ ระบบจะแจ้งเตือนเมื่อเหลือเวลา 8 ชั่วโมง</p></div></div></div></aside></div>
 </AppShell>;
}
