"use client";

import Link from "next/link";
import { useMemo, useState } from "react";
import { ChevronRight, Search } from "lucide-react";
import { StatusBadge } from "../components/ui";
import type { RequestStatus } from "../lib/mock-data";

type Task = { id: string; title: string; requester: string; unit: string; amount: number; due: string; status: RequestStatus; step: string };
export function TasksClient({ tasks }: { tasks: Task[] }) {
  const [filter, setFilter] = useState<"all"|"overdue"|"active">("all"); const [query, setQuery] = useState("");
  const rows = useMemo(() => tasks.filter((task) => (filter === "all" || (filter === "overdue" ? task.status === "เกินกำหนด" : task.status !== "เกินกำหนด")) && `${task.id} ${task.title} ${task.requester}`.toLowerCase().includes(query.toLowerCase())), [tasks,filter,query]);
  const overdue = tasks.filter((task) => task.status === "เกินกำหนด").length;
  return <section className="mt-6 border border-[var(--line-dark)] bg-[var(--paper)]"><div className="flex flex-wrap gap-2 border-b border-[var(--line)] p-4"><button onClick={() => setFilter("all")} aria-pressed={filter === "all"} className={`min-h-10 border px-4 font-semibold ${filter === "all" ? "border-[var(--graphite)] bg-[var(--graphite)] text-white" : "border-[var(--line)]"}`}>ทั้งหมด {tasks.length}</button><button onClick={() => setFilter("active")} aria-pressed={filter === "active"} className={`min-h-10 border px-4 font-semibold ${filter === "active" ? "border-[var(--graphite)] bg-[var(--graphite)] text-white" : "border-[var(--line)]"}`}>ตามกำหนด {tasks.length-overdue}</button><button onClick={() => setFilter("overdue")} aria-pressed={filter === "overdue"} className={`min-h-10 border px-4 font-semibold ${filter === "overdue" ? "border-[var(--red)] bg-[var(--red)] text-white" : "border-[var(--line)] text-[var(--red)]"}`}>เกินกำหนด {overdue}</button><label className="relative ml-auto min-w-64"><span className="sr-only">ค้นหางาน</span><Search size={16} className="absolute left-3 top-1/2 -translate-y-1/2 text-stone-500"/><input value={query} onChange={(e)=>setQuery(e.target.value)} className="min-h-10 w-full border border-[var(--line)] pl-9 pr-3 text-base" placeholder="ค้นหาเลขคำขอหรือเรื่อง"/></label></div><div className="divide-y divide-[var(--line)]">{rows.length ? rows.map((task,index) => <Link href={`/requests/${task.id}`} key={task.id} className={`group grid gap-3 p-4 hover:bg-orange-50/60 sm:grid-cols-[auto_1fr_auto] ${task.status === "เกินกำหนด" ? "hazard" : ""}`}><div className="flex h-11 w-11 items-center justify-center border border-[var(--line-dark)] bg-white font-bold">{index+1}</div><div className="bg-[var(--paper)]/90 px-2"><div className="flex flex-wrap items-center gap-2"><span className="font-bold">{task.id}</span><StatusBadge status={task.status}/></div><h2 className="mt-1 font-semibold">{task.title}</h2><p className="mt-1 text-xs text-stone-600">{task.requester} · {task.unit} · {task.amount.toLocaleString("th-TH")} บาท</p><p className="mt-1 text-xs font-semibold text-stone-700">{task.step}</p></div><div className="flex items-center gap-3 bg-[var(--paper)]/90 px-2"><div className="text-right text-xs"><div className="font-semibold">กำหนด {task.due}</div></div><ChevronRight className="transition-transform group-hover:translate-x-1"/></div></Link>) : <p className="p-10 text-center text-stone-600">ไม่มีงานที่ตรงกับตัวกรอง</p>}</div></section>;
}
