import Link from "next/link";
import { AppShell } from "../components/app-shell";
import { Download, FilePlus2, Filter, Search } from "../components/icons";
import { Button, PageHeader, StatusBadge } from "../components/ui";
import { getRequests } from "../lib/live-data";

export default async function RequestsPage() {
  const { rows: requests, error } = await getRequests();
  return <AppShell><PageHeader title="คำขอของฉัน" description="สร้าง ติดตาม และตรวจสอบประวัติคำขอหลักการกับคำขอเบิกจ่ายของคุณ" action={<Link href="/requests/new" className="inline-flex min-h-10 items-center justify-center gap-2 border border-[var(--orange-dark)] bg-[var(--orange)] px-4 font-semibold text-white hover:bg-[var(--orange-dark)]"><FilePlus2 size={18}/>สร้างคำขอใหม่</Link>}/>
    {error&&<div role="alert" className="mt-5 border border-red-300 bg-[var(--red-soft)] p-4 text-[var(--red)]"><strong>ยังอ่านข้อมูลจากฐานข้อมูลไม่ได้</strong><p className="mt-1 text-sm">กรุณารัน migration ในโฟลเดอร์ supabase/migrations แล้วลองใหม่ · {error}</p></div>}
    <div className="mt-6 border border-[var(--line-dark)] bg-[var(--paper)]"><div className="flex flex-col gap-3 border-b border-[var(--line)] p-4 lg:flex-row lg:items-center"><div className="flex border border-[var(--line-dark)]"><button className="min-h-10 bg-[var(--graphite)] px-4 font-semibold text-white">ทั้งหมด <span className="ml-1 bg-white px-1.5 text-xs text-[var(--graphite)]">27</span></button><button className="min-h-10 border-l border-[var(--line-dark)] px-4 font-semibold hover:bg-stone-100">ร่าง 3</button><button className="min-h-10 border-l border-[var(--line-dark)] px-4 font-semibold hover:bg-stone-100">ส่งกลับ 2</button></div><label className="relative ml-auto min-w-72 flex-1 lg:max-w-md"><span className="sr-only">ค้นหาคำขอ</span><Search size={17} className="absolute left-3 top-1/2 -translate-y-1/2 text-stone-500"/><input className="min-h-10 w-full border border-[var(--line)] pl-9 pr-3" placeholder="ค้นหาเลขคำขอหรือชื่อเรื่อง"/></label><Button variant="secondary"><Filter size={17}/>ตัวกรอง</Button><Button variant="secondary"><Download size={17}/>ส่งออก</Button></div>
      <div className="scrollbar-thin overflow-x-auto"><table className="w-full min-w-[980px] border-collapse text-left"><thead className="bg-stone-100"><tr>{["เลขที่คำขอ","ประเภท","ชื่อเรื่อง","วันที่สร้าง","วงเงิน (บาท)","สถานะ","ขั้นตอนปัจจุบัน",""].map(h=><th key={h} className="border-b border-r border-[var(--line)] px-4 py-3 text-xs font-bold last:border-r-0">{h}</th>)}</tr></thead><tbody>{requests.map(r=><tr key={r.id} className="hover:bg-orange-50/60"><td className="border-b border-r border-[var(--line)] px-4 py-4 font-bold">{r.id}</td><td className="border-b border-r border-[var(--line)] px-4 py-4">{r.type}</td><td className="max-w-sm border-b border-r border-[var(--line)] px-4 py-4"><div className="font-semibold">{r.title}</div><div className="mt-1 text-xs text-stone-500">{r.unit}</div></td><td className="border-b border-r border-[var(--line)] px-4 py-4">{r.date}</td><td className="border-b border-r border-[var(--line)] px-4 py-4 text-right tabular-nums">{r.amount.toLocaleString("th-TH",{minimumFractionDigits:2})}</td><td className="border-b border-r border-[var(--line)] px-4 py-4"><StatusBadge status={r.status}/></td><td className="border-b border-r border-[var(--line)] px-4 py-4">{r.step}</td><td className="border-b border-[var(--line)] px-4 py-4"><Link href={`/requests/${r.id}`} className="inline-flex min-h-9 items-center border border-[var(--line-dark)] px-3 font-semibold hover:bg-stone-100">ดูรายละเอียด</Link></td></tr>)}</tbody></table></div>
      <div className="flex items-center justify-between border-t border-[var(--line)] p-4 text-sm"><span>แสดง 1–6 จาก 27 รายการ</span><nav className="flex" aria-label="แบ่งหน้ารายการคำขอ"><button aria-label="หน้าก่อนหน้า" className="h-9 w-9 border border-[var(--line)]">‹</button><button aria-current="page" aria-label="หน้า 1" className="h-9 w-9 bg-[var(--orange)] font-bold text-white">1</button><button aria-label="หน้า 2" className="h-9 w-9 border border-[var(--line)]">2</button><button aria-label="หน้า 3" className="h-9 w-9 border border-[var(--line)]">3</button><button aria-label="หน้าถัดไป" className="h-9 w-9 border border-[var(--line)]">›</button></nav></div>
    </div>
  </AppShell>;
}
