"use client";

import Link from "next/link";
import { useMemo, useState } from "react";
import { Download, Search } from "lucide-react";
import { StatusBadge } from "../components/ui";
import type { RequestStatus } from "../lib/mock-data";

export type RequestRow = { id: string; type: string; title: string; unit: string; date: string; amount: number; status: RequestStatus; step: string };
const pageSize = 10;

export function RequestsClient({ requests }: { requests: RequestRow[] }) {
  const [query, setQuery] = useState(""); const [status, setStatus] = useState("all"); const [kind, setKind] = useState("all"); const [page, setPage] = useState(1);
  const rows = useMemo(() => requests.filter((row) => (status === "all" || row.status === status) && (kind === "all" || row.type === kind) && `${row.id} ${row.title} ${row.unit}`.toLowerCase().includes(query.toLowerCase())), [requests, query, status, kind]);
  const pages = Math.max(1, Math.ceil(rows.length / pageSize)); const visible = rows.slice((Math.min(page, pages) - 1) * pageSize, Math.min(page, pages) * pageSize);
  function exportCsv() { const csv = [["เลขคำขอ","ประเภท","ชื่อเรื่อง","วันที่","วงเงิน","สถานะ","ขั้นตอน"], ...rows.map((r) => [r.id,r.type,r.title,r.date,String(r.amount),r.status,r.step])].map((line) => line.map((cell) => `"${String(cell).replaceAll('"','""')}"`).join(",")).join("\r\n"); const blob = new Blob(["\uFEFF" + csv], { type: "text/csv;charset=utf-8" }); const url = URL.createObjectURL(blob); const link = document.createElement("a"); link.href = url; link.download = `procurement-requests-${new Date().toISOString().slice(0,10)}.csv`; link.click(); URL.revokeObjectURL(url); }
  return <div className="mt-6 border border-[var(--line-dark)] bg-[var(--paper)]"><div className="flex flex-col gap-3 border-b border-[var(--line)] p-4 lg:flex-row lg:items-center"><label className="relative min-w-72 flex-1 lg:max-w-md"><span className="sr-only">ค้นหาคำขอ</span><Search size={17} className="absolute left-3 top-1/2 -translate-y-1/2 text-stone-500"/><input value={query} onChange={(e) => { setQuery(e.target.value); setPage(1); }} className="min-h-11 w-full border border-[var(--line)] pl-9 pr-3 text-base" placeholder="ค้นหาเลขคำขอ ชื่อเรื่อง หรือหน่วยงาน"/></label><select aria-label="กรองประเภท" value={kind} onChange={(e) => { setKind(e.target.value); setPage(1); }} className="min-h-11 border border-[var(--line-dark)] bg-white px-3 text-base"><option value="all">ทุกประเภท</option><option value="ซื้อ">จัดซื้อ</option><option value="จ้าง">จัดจ้าง</option></select><select aria-label="กรองสถานะ" value={status} onChange={(e) => { setStatus(e.target.value); setPage(1); }} className="min-h-11 border border-[var(--line-dark)] bg-white px-3 text-base"><option value="all">ทุกสถานะ</option>{Array.from(new Set(requests.map((r) => r.status))).map((value) => <option key={value}>{value}</option>)}</select><button type="button" onClick={exportCsv} disabled={!rows.length} className="inline-flex min-h-11 items-center justify-center gap-2 border border-[var(--line-dark)] bg-white px-4 font-semibold disabled:opacity-50"><Download size={17}/>ส่งออก CSV</button></div>
    <div className="overflow-x-auto"><table className="w-full min-w-[980px] border-collapse text-left"><thead className="bg-stone-100"><tr>{["เลขที่คำขอ","ประเภท","ชื่อเรื่อง","วันที่สร้าง","วงเงิน (บาท)","สถานะ","ขั้นตอนปัจจุบัน",""].map((h) => <th key={h} className="border-b border-r border-[var(--line)] px-4 py-3 text-xs font-bold last:border-r-0">{h}</th>)}</tr></thead><tbody>{visible.length ? visible.map((r) => <tr key={r.id} className="hover:bg-orange-50/60"><td className="border-b border-r border-[var(--line)] px-4 py-4 font-bold">{r.id}</td><td className="border-b border-r border-[var(--line)] px-4 py-4">{r.type}</td><td className="max-w-sm border-b border-r border-[var(--line)] px-4 py-4"><div className="font-semibold">{r.title}</div><div className="mt-1 text-xs text-stone-500">{r.unit}</div></td><td className="border-b border-r border-[var(--line)] px-4 py-4">{r.date}</td><td className="border-b border-r border-[var(--line)] px-4 py-4 text-right tabular-nums">{r.amount.toLocaleString("th-TH",{minimumFractionDigits:2})}</td><td className="border-b border-r border-[var(--line)] px-4 py-4"><StatusBadge status={r.status}/></td><td className="border-b border-r border-[var(--line)] px-4 py-4">{r.step}</td><td className="border-b border-[var(--line)] px-4 py-4"><Link href={`/requests/${r.id}`} className="inline-flex min-h-9 items-center border border-[var(--line-dark)] px-3 font-semibold hover:bg-stone-100">ดูรายละเอียด</Link></td></tr>) : <tr><td colSpan={8} className="p-10 text-center text-stone-600">ไม่พบคำขอที่ตรงกับตัวกรอง</td></tr>}</tbody></table></div>
    <div className="flex items-center justify-between border-t border-[var(--line)] p-4 text-sm"><span>แสดง {visible.length} จาก {rows.length} รายการ</span><nav className="flex items-center gap-1" aria-label="แบ่งหน้ารายการคำขอ"><button disabled={page <= 1} onClick={() => setPage((p) => p - 1)} className="min-h-9 border border-[var(--line)] px-3 disabled:opacity-40">ก่อนหน้า</button><span className="px-3">หน้า {Math.min(page,pages)} / {pages}</span><button disabled={page >= pages} onClick={() => setPage((p) => p + 1)} className="min-h-9 border border-[var(--line)] px-3 disabled:opacity-40">ถัดไป</button></nav></div>
  </div>;
}
