import Link from "next/link";
import { AlertTriangle, CheckCircle2, ChevronRight, ClipboardCheck, FilePlus2, FileText } from "lucide-react";
import { AppShell } from "./components/app-shell";
import { PageHeader, StatusBadge } from "./components/ui";
import { getCurrentProfile, getMyTasks, getRequests } from "./lib/live-data";

export default async function Home() {
  const [{ rows: requests, error }, { rows: tasks }, profile] = await Promise.all([getRequests(), getMyTasks(), getCurrentProfile()]);
  const overdue = tasks.filter((task) => task.status === "เกินกำหนด"); const completed = requests.filter((request) => request.status === "เสร็จสิ้น"); const total = requests.reduce((sum,request)=>sum+request.amount,0);
  return <AppShell><PageHeader title={`สวัสดี ${profile?.full_name || "ผู้ใช้งาน"}`} description="ภาพรวมคำขอและงานที่ต้องดำเนินการจากข้อมูลปัจจุบัน" action={<Link href="/requests/new" className="inline-flex min-h-10 items-center justify-center gap-2 border border-[var(--orange-dark)] bg-[var(--orange)] px-4 font-semibold text-white"><FilePlus2 size={18}/>สร้างคำขอใหม่</Link>}/>{error&&<div role="alert" className="mt-5 border border-red-300 bg-[var(--red-soft)] p-4 text-[var(--red)]">{error}</div>}
    <section className="mt-6 grid border border-[var(--line-dark)] bg-[var(--paper)] sm:grid-cols-2 xl:grid-cols-4">{[{label:"คำขอที่เข้าถึงได้",value:requests.length,unit:"รายการ",icon:FileText,href:"/requests"},{label:"งานรอดำเนินการ",value:tasks.length,unit:"งาน",icon:ClipboardCheck,href:"/tasks"},{label:"งานเกินกำหนด",value:overdue.length,unit:"งาน",icon:AlertTriangle,href:"/tasks"},{label:"คำขอเสร็จสิ้น",value:completed.length,unit:"รายการ",icon:CheckCircle2,href:"/reports"}].map(({label,value,unit,icon:Icon,href},i)=><Link href={href} key={label} className={`flex min-h-32 items-center gap-4 p-5 hover:bg-orange-50 ${i?"border-t border-[var(--line)] sm:border-l sm:border-t-0":""}`}><Icon size={28}/><span><span className="block text-sm text-stone-600">{label}</span><span className="block text-3xl font-bold tabular-nums text-[var(--orange)]">{value}<small className="ml-1 text-sm font-normal text-stone-600">{unit}</small></span></span><ChevronRight className="ml-auto" size={18}/></Link>)}</section>
    <div className="mt-5 grid gap-5 xl:grid-cols-[1.4fr_1fr]"><section className="border border-[var(--line-dark)] bg-[var(--paper)]"><div className="flex items-center justify-between border-b border-[var(--line)] p-4"><h2 className="text-lg font-bold">งานที่ต้องดำเนินการ</h2><Link href="/tasks" className="inline-flex items-center gap-1 font-semibold text-[var(--orange-dark)]">ดูทั้งหมด <ChevronRight size={16}/></Link></div><div className="divide-y divide-[var(--line)]">{tasks.slice(0,5).length?tasks.slice(0,5).map((task)=><Link href={`/requests/${task.id}`} key={task.id} className="grid gap-2 p-4 hover:bg-orange-50 sm:grid-cols-[1fr_auto]"><div><div className="flex flex-wrap items-center gap-2"><strong>{task.id}</strong><StatusBadge status={task.status}/></div><p className="mt-1 font-semibold">{task.title}</p><p className="mt-1 text-xs text-stone-500">{task.step} · {task.unit}</p></div><span className="self-center text-sm font-semibold">{task.due}</span></Link>):<p className="p-8 text-center text-stone-600">ไม่มีงานรอดำเนินการ</p>}</div></section><aside className="border border-[var(--line-dark)] bg-[var(--paper)]"><h2 className="border-b border-[var(--line)] p-4 text-lg font-bold">สรุปวงเงิน</h2><dl className="divide-y divide-[var(--line)]"><div className="p-4"><dt className="text-sm text-stone-500">วงเงินคำขอทั้งหมด</dt><dd className="mt-1 text-2xl font-bold tabular-nums">{total.toLocaleString("th-TH",{minimumFractionDigits:2})} บาท</dd></div><div className="p-4"><dt className="text-sm text-stone-500">จำนวนคำขอ</dt><dd className="mt-1 text-xl font-bold">{requests.length} รายการ</dd></div></dl><Link href="/reports" className="m-4 flex min-h-11 items-center justify-center border border-[var(--line-dark)] font-semibold hover:bg-stone-100">เปิดรายงาน</Link></aside></div>
  </AppShell>;
}
