import Link from "next/link";
import { AppShell } from "./components/app-shell";
import { AlertTriangle, Check, CheckCircle2, ChevronRight, Clock3, FilePlus2, Search, SlidersHorizontal, UserRound } from "./components/icons";
import { Button, PageHeader, StatusBadge } from "./components/ui";
import { approvalSteps } from "./lib/mock-data";
import { getCurrentProfile, getRequests } from "./lib/live-data";

export default async function Home() {
  const [{ rows: requests, error }, profile] = await Promise.all([getRequests(), getCurrentProfile()]);
  const overdue = requests.filter((request)=>request.status === "เกินกำหนด").length;
  return <AppShell><PageHeader title={`สวัสดี ${profile?.full_name || "ผู้ใช้งาน"}`} description={`มีคำขอที่คุณเข้าถึงได้ ${requests.length} รายการ และ ${overdue} รายการเกินกำหนด`} action={<Link href="/requests/new" className="inline-flex min-h-10 items-center justify-center gap-2 border border-[var(--orange-dark)] bg-[var(--orange)] px-4 font-semibold text-white hover:bg-[var(--orange-dark)]"><FilePlus2 size={18}/>สร้างคำขอใหม่</Link>} />
    {error&&<div role="alert" className="mt-5 border border-red-300 bg-[var(--red-soft)] p-4 text-[var(--red)]"><strong>ยังอ่านข้อมูลจากฐานข้อมูลไม่ได้</strong><p className="mt-1 text-sm">กรุณารัน migration ก่อนใช้งาน · {error}</p></div>}
    <section className="paper-grid mt-6 border border-[var(--line-dark)]" aria-labelledby="workflow-heading"><div className="flex items-center justify-between border-b border-[var(--line)] px-4 py-3"><div><h2 id="workflow-heading" className="text-lg font-bold">สายงานอนุมัติที่กำลังดำเนินการ</h2><p className="text-xs text-stone-500">แสดงแบบกลุ่มจากกระบวนการหลัก 12 ขั้นตอน · เปิดรายการเพื่อดูผู้เห็นชอบแต่ละตำแหน่ง</p></div><Link href="/process" className="inline-flex items-center gap-1 font-semibold text-[var(--orange-dark)] hover:underline">ดูภาพรวมทั้งหมด <ChevronRight size={16}/></Link></div><div className="scrollbar-thin overflow-x-auto p-4"><div className="signal-in flex min-w-[1000px] items-stretch">{approvalSteps.map((step, i) => <div key={step.n} className="flex flex-1 items-center"><div className={`relative flex min-h-36 flex-1 flex-col border p-3 ${step.state === "current" ? "border-[var(--orange)] bg-[var(--orange-soft)]" : step.state === "overdue" ? "hazard border-[var(--orange)]" : "border-[var(--line-dark)] bg-[var(--paper)]"}`}><span className="mb-4 flex h-7 w-7 items-center justify-center border border-current bg-white text-xs font-bold">{step.n}</span>{step.state === "current" && <span className="absolute -top-3 right-2 bg-[var(--orange)] px-2 py-1 text-xs font-bold text-white">ขั้นตอนปัจจุบัน</span>}<div className="mt-auto"><div className="font-bold">{step.short}</div><div className="mt-1 text-xs text-stone-600">{step.count} งานในขั้นตอน</div><div className="mt-2 flex items-center gap-1.5 text-xs font-semibold">{step.state === "done" ? <><CheckCircle2 size={15} className="text-[var(--green)]"/>เสร็จแล้ว</> : step.state === "overdue" ? <><AlertTriangle size={15} className="text-[var(--red)]"/>เกินกำหนด</> : <><Clock3 size={15}/>รอดำเนินการ</>}</div></div></div>{i < approvalSteps.length - 1 && <ChevronRight className="mx-1 shrink-0" size={20}/>}</div>)}</div></div></section>
    <section className="mt-5 grid border border-[var(--line-dark)] bg-[var(--paper)] sm:grid-cols-2 xl:grid-cols-4">{[{label:"รอตรวจสอบ",value:5,icon:Search},{label:"รอเห็นชอบ",value:3,icon:UserRound},{label:"เกินกำหนด",value:2,icon:AlertTriangle},{label:"เสร็จสิ้นวันนี้",value:8,icon:Check}].map(({label,value,icon:Icon},i)=><div key={label} className={`flex items-center gap-4 p-5 ${i ? "border-t border-[var(--line)] sm:border-l sm:border-t-0" : ""}`}><Icon size={28}/><div><div className="text-sm text-stone-600">{label}</div><div className="text-3xl font-bold tabular-nums text-[var(--orange)]">{value}<span className="ml-1 text-sm font-normal text-stone-600">งาน</span></div></div></div>)}</section>
    <section className="mt-5 border border-[var(--line-dark)] bg-[var(--paper)]"><div className="flex flex-col gap-3 border-b border-[var(--line)] p-4 md:flex-row md:items-center"><h2 className="text-lg font-bold">งานที่ต้องดำเนินการ</h2><div className="ml-auto flex flex-wrap gap-2"><select className="min-h-10 border border-[var(--line)] bg-white px-3"><option>คำขอทุกประเภท</option><option>คำขอหลักการ</option><option>คำขอเบิกจ่าย</option></select><Button variant="secondary"><SlidersHorizontal size={16}/>ตัวกรอง</Button></div></div><div className="scrollbar-thin overflow-x-auto"><table className="w-full min-w-[960px] border-collapse text-left"><thead className="bg-stone-100 text-xs uppercase"><tr>{["เลขที่คำขอ","เรื่อง","ผู้ยื่น / หน่วยงาน","วงเงิน (บาท)","กำหนด","สถานะ","ขั้นตอนปัจจุบัน",""].map(h=><th key={h} className="border-b border-r border-[var(--line)] px-3 py-3 font-bold last:border-r-0">{h}</th>)}</tr></thead><tbody>{requests.slice(0,5).map(r=><tr key={r.id} className="hover:bg-orange-50/50"><td className="border-b border-r border-[var(--line)] px-3 py-3 font-semibold"><Link href={`/requests/${r.id}`} className="hover:text-[var(--orange-dark)] hover:underline">{r.id}</Link></td><td className="max-w-sm border-b border-r border-[var(--line)] px-3 py-3">{r.title}</td><td className="border-b border-r border-[var(--line)] px-3 py-3"><span className="block font-medium">{r.requester}</span><span className="text-xs text-stone-500">{r.unit}</span></td><td className="border-b border-r border-[var(--line)] px-3 py-3 text-right tabular-nums">{r.amount.toLocaleString("th-TH",{minimumFractionDigits:2})}</td><td className={`border-b border-r border-[var(--line)] px-3 py-3 ${r.status === "เกินกำหนด" ? "font-semibold text-[var(--red)]" : ""}`}>{r.due}</td><td className="border-b border-r border-[var(--line)] px-3 py-3"><StatusBadge status={r.status}/></td><td className="border-b border-r border-[var(--line)] px-3 py-3">{r.step}</td><td className="border-b border-[var(--line)] px-3 py-3"><Link href={`/requests/${r.id}`} className="inline-flex min-h-9 items-center border border-[var(--line-dark)] px-3 font-semibold hover:bg-stone-100">เปิดงาน</Link></td></tr>)}</tbody></table></div></section>
  </AppShell>;
}
