import { AppShell } from "../components/app-shell";
import { AlertTriangle, CheckCircle2, FileText, Filter, Plus, Search } from "../components/icons";
import { Button, PageHeader } from "../components/ui";
import { processColumns } from "../lib/mock-data";

export default function ProcessPage() {
 return <AppShell><PageHeader title="ภาพรวมกระบวนการ" description="ติดตามปริมาณงาน จุดค้าง และการไหลของคำขอในทุกขั้นตอน" action={<Button><Plus size={18}/>สร้างคำขอ</Button>}/>
  <div className="mt-5 flex flex-wrap gap-2 border border-[var(--line-dark)] bg-[var(--paper)] p-3"><select className="min-h-10 border border-[var(--line)] px-3"><option>ทุกประเภทคำขอ</option></select><select className="min-h-10 border border-[var(--line)] px-3"><option>ทุกหน่วยงาน</option></select><select className="min-h-10 border border-[var(--line)] px-3"><option>ทุกผู้รับผิดชอบ</option></select><label className="relative ml-auto min-w-60"><Search size={16} className="absolute left-3 top-1/2 -translate-y-1/2"/><input className="min-h-10 w-full border border-[var(--line)] pl-9 pr-3" placeholder="ค้นหาในกระบวนการ"/></label><Button variant="secondary"><Filter size={16}/>ตัวกรอง</Button></div>
  <div className="mt-4 grid gap-4 xl:grid-cols-[minmax(0,1fr)_300px]"><section className="scrollbar-thin overflow-x-auto border border-[var(--line-dark)] bg-[var(--paper)]"><div className="grid min-w-[1050px] grid-cols-5 divide-x divide-[var(--line)]">{processColumns.map((col,ci)=><div key={col.title} className="min-h-[640px]"><div className="flex items-center gap-2 border-b border-[var(--line-dark)] bg-stone-100 p-3"><span className="flex h-8 w-8 items-center justify-center border border-[var(--line-dark)] bg-white">{ci === 4 ? <CheckCircle2 size={18} className="text-[var(--green)]"/> : <FileText size={18}/>}</span><h2 className="font-bold">{col.title}</h2><span className="ml-auto border border-[var(--line)] bg-white px-2 py-0.5 text-xs font-bold">{col.count}</span></div><div className="space-y-3 p-3">{col.items.map((r,ri)=><article key={`${col.title}-${r.id}-${ri}`} className={`border border-[var(--line-dark)] bg-white p-3 ${r.status === "เกินกำหนด" ? "hazard" : ""}`}><div className={r.status === "เกินกำหนด" ? "bg-white/95 p-2" : ""}><div className="flex items-start gap-2"><FileText size={16} className="mt-0.5 shrink-0"/><span className="font-bold">{r.id}</span>{r.status === "เกินกำหนด" && <AlertTriangle size={16} className="ml-auto text-[var(--red)]"/>}</div><h3 className="mt-2 line-clamp-2 text-sm font-semibold">{r.title}</h3><div className="mt-3 flex items-end justify-between text-xs text-stone-600"><span>{r.requester}</span><span className={r.status === "เสร็จสิ้น" ? "text-[var(--green)]" : ""}>{r.status === "เสร็จสิ้น" ? "เสร็จแล้ว" : `${ri+1} วัน`}</span></div></div></article>)}<button className="w-full border border-dashed border-[var(--line-dark)] p-2 text-sm font-semibold hover:bg-stone-100">+ ดูเพิ่มเติม ({Math.max(0,col.count-col.items.length)})</button></div></div>)}</div></section>
  <aside className="space-y-4"><div className="border border-[var(--line-dark)] bg-[var(--paper)]"><h2 className="border-b border-[var(--line)] p-4 text-lg font-bold">งานวันนี้</h2><dl className="divide-y divide-[var(--line)]">{[["รอการตรวจสอบ","12"],["รอการเห็นชอบ","8"],["รอการคุมยอด","6"],["รอการอนุมัติ","5"],["เสร็จสิ้นวันนี้","4"]].map(([k,v])=><div key={k} className="flex justify-between p-3"><dt>{k}</dt><dd className="font-bold">{v}</dd></div>)}</dl></div><div className="border border-[var(--line-dark)] bg-[var(--paper)] p-4"><h2 className="text-lg font-bold">ภาพรวมงบประมาณ</h2><p className="mt-1 text-xs text-stone-500">ข้อมูลจำลอง ปีงบประมาณ 2567</p><dl className="mt-4 space-y-3 text-sm"><div className="flex justify-between"><dt>งบประมาณที่ได้รับ</dt><dd className="font-semibold">250,000,000.00</dd></div><div className="flex justify-between"><dt>ใช้ไปแล้ว</dt><dd className="font-semibold">128,450,750.00</dd></div><div className="flex justify-between"><dt>คงเหลือ</dt><dd className="font-semibold text-[var(--green)]">121,549,250.00</dd></div></dl><div className="mt-4 h-3 bg-stone-200"><div className="h-full w-[51%] bg-[var(--orange)]"/></div><div className="mt-1 text-right text-xs">ใช้จ่าย 51.38%</div></div><div className="border border-[var(--orange)] bg-[var(--orange-soft)] p-4"><div className="flex gap-3"><AlertTriangle className="text-[var(--orange-dark)]"/><div><h2 className="font-bold">7 งานเกินกำหนด</h2><p className="mt-1 text-sm">มากที่สุดอยู่ในขั้นตรวจสอบเอกสาร</p></div></div></div></aside></div>
 </AppShell>;
}
